export const ACTS_REQUEST = "ACTS_REQUEST";
export const ACTS_SUCCESS = "ACTS_SUCCESS";
export const ACTS_FAIL = "ACTS_FAIL";
export const CLEAR_ERRORSA="CLEAR_ERRORS"



export const CONDITIONS_REQUEST = "CONDITIONS_REQUEST";
export const CONDITIONS_SUCCESS = "CONDITIONS_SUCCESS";
export const CONDITIONS_FAIL = "CONDITIONS_FAIL";
export const CLEAR_ERRORSC="CLEAR_ERRORS"


// por ID para actos

export const ACT_ID_REQUEST="ACT_ID_REQUEST";
export const ACT_ID_SUCCESS="ACT_ID_SUCCESS";
export const ACT_ID_FAIL="ACT_ID_FAIL"
export const CLEAR_ERRORSAI="CLEAR_ERRORSAI"

// por ID para condiciones

export const CONDITION_ID_REQUEST="CONDITION_ID_REQUEST";
export const CONDITION_ID_SUCCESS="CONDITION_ID_SUCCESS";
export const CONDITION_ID_FAIL="CONDITION_ID_FAIL"
export const CLEAR_ERRORSCI="CLEAR_ERRORSCI"

// Crear un acto inseguro

export const CREATE_ACT_REQUEST="CREATE_ACT_REQUEST";
export const CREATE_ACT_SUCCESS="CREATE_ACT_SUCCESS";
export const CREATE_ACT_FAIL="CREATE_ACT_FAIL"

// Crear una condicion insegura

export const CREATE_CONDITION_REQUEST="CREATE_CONDITION_REQUEST";
export const CREATE_CONDITION_SUCCESS="CREATE_CONDITION_SUCCESS";
export const CREATE_CONDITION_FAIL="CREATE_CONDITION_FAIL";
